name = input(f"enter name:")
type(name)
age = input(f"enter age:")
type(age)
country = input(f"enter country:")
type(country)
state = input(f"enter state:")
type(state)
qualification = input(f"enter qualification:")
type(qualification)
